[package]
name = "fox-monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
ctrlc = "3.4.5"
env_logger = "0.11.7"
foxglove = "0.4.0"
schemars = "0.8.22"
serde = "1.0.219"
sysinfo = "0.33.1"
